// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCpQs0ko453BgUBQL1rI8MLgMwCYoHWr4',
    appId: '1:908977168629:web:15019f16da398ee67ce5bc',
    messagingSenderId: '908977168629',
    projectId: 'admin-4da9b',
    authDomain: 'admin-4da9b.firebaseapp.com',
    storageBucket: 'admin-4da9b.appspot.com',
    measurementId: 'G-X8C50YB2Z0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_lO4jRPJjPk0uGCMJ5ttFDikp8Y1lvTo',
    appId: '1:908977168629:android:8394bd050ae907267ce5bc',
    messagingSenderId: '908977168629',
    projectId: 'admin-4da9b',
    storageBucket: 'admin-4da9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADKhfwWj7wYeLxhWJM9dIXAWZJ0XIadAU',
    appId: '1:908977168629:ios:ce559bab356062557ce5bc',
    messagingSenderId: '908977168629',
    projectId: 'admin-4da9b',
    storageBucket: 'admin-4da9b.appspot.com',
    iosBundleId: 'com.example.shopsmartUsers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADKhfwWj7wYeLxhWJM9dIXAWZJ0XIadAU',
    appId: '1:908977168629:ios:ce559bab356062557ce5bc',
    messagingSenderId: '908977168629',
    projectId: 'admin-4da9b',
    storageBucket: 'admin-4da9b.appspot.com',
    iosBundleId: 'com.example.shopsmartUsers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCpQs0ko453BgUBQL1rI8MLgMwCYoHWr4',
    appId: '1:908977168629:web:9dadb5ab4578d4e37ce5bc',
    messagingSenderId: '908977168629',
    projectId: 'admin-4da9b',
    authDomain: 'admin-4da9b.firebaseapp.com',
    storageBucket: 'admin-4da9b.appspot.com',
    measurementId: 'G-KDM38BPEV4',
  );
}
